Repository jenkins-x-charts/jx-build-templates, pull requests merged in 2018-11, with the labels that each got.

#45 Reduce CPU request to .5
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-csharp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-filerunner-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-buildtemplate.yaml
  jx-build-templates/templates/jenkins-gradle-buildtemplate.yaml
  jx-build-templates/templates/jenkins-javascript-buildtemplate.yaml
  jx-build-templates/templates/jenkins-jenkins-buildtemplate.yaml
  jx-build-templates/templates/jenkins-maven-buildtemplate.yaml
  jx-build-templates/templates/jenkins-python-buildtemplate.yaml
  jx-build-templates/templates/jenkins-rust-buildtemplate.yaml
  jx-build-templates/templates/jenkins-scala-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
Labels: approved, size/S

#52 switch jenkins x helm repo
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
Labels: approved, size/XS

#54 fix: removed references to depreacted chartmuseum instance
  jx-build-templates/Makefile
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
Labels: approved, size/XS

#68 try and fix OOM issues on Jenkins X infra running go builds
  jx-build-templates/templates/jenkins-go-buildtemplate.yaml
Labels: approved, size/XS

#70 increase default timeout of 10 mins to 60 mins
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-csharp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-filerunner-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-buildtemplate.yaml
  jx-build-templates/templates/jenkins-gradle-buildtemplate.yaml
  jx-build-templates/templates/jenkins-javascript-buildtemplate.yaml
  jx-build-templates/templates/jenkins-jenkins-buildtemplate.yaml
  jx-build-templates/templates/jenkins-maven-buildtemplate.yaml
  jx-build-templates/templates/jenkins-python-buildtemplate.yaml
  jx-build-templates/templates/jenkins-rust-buildtemplate.yaml
  jx-build-templates/templates/jenkins-scala-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-ci-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-release-buildtemplate.yaml
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
Labels: approved, size/S

#71 use new jvm flags on all build templates since the golang one looks good after a day of testing
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-csharp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-filerunner-buildtemplate.yaml
  jx-build-templates/templates/jenkins-gradle-buildtemplate.yaml
  jx-build-templates/templates/jenkins-javascript-buildtemplate.yaml
  jx-build-templates/templates/jenkins-jenkins-buildtemplate.yaml
  jx-build-templates/templates/jenkins-maven-buildtemplate.yaml
  jx-build-templates/templates/jenkins-python-buildtemplate.yaml
  jx-build-templates/templates/jenkins-rust-buildtemplate.yaml
  jx-build-templates/templates/jenkins-scala-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
Labels: approved, size/S

#84 add environment build templates
  jx-build-templates/templates/environment-apply-buildtemplate.yaml
  jx-build-templates/templates/environment-build-buildtemplate.yaml
Labels: approved, size/M

#85 switch APPLY_NAMESPACE to an env var set in prowconfig
  jx-build-templates/templates/environment-apply-buildtemplate.yaml
Labels: approved, size/XS

#86 avoid jenkins service account as it runs as cluster admin
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-csharp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-filerunner-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-buildtemplate.yaml
  jx-build-templates/templates/jenkins-gradle-buildtemplate.yaml
  jx-build-templates/templates/jenkins-javascript-buildtemplate.yaml
  jx-build-templates/templates/jenkins-jenkins-buildtemplate.yaml
  jx-build-templates/templates/jenkins-maven-buildtemplate.yaml
  jx-build-templates/templates/jenkins-python-buildtemplate.yaml
  jx-build-templates/templates/jenkins-rust-buildtemplate.yaml
  jx-build-templates/templates/jenkins-scala-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
Labels: approved, size/S

#89 fix working directory for helm based builds
  jx-build-templates/templates/environment-apply-buildtemplate.yaml
  jx-build-templates/templates/environment-build-buildtemplate.yaml
Labels: approved, size/XS
