Repository jenkins-x-charts/jx-build-templates, pull requests merged in 2018-10, with the labels that each got.

#2 add an addon deploy template
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
  jx-build-templates/values.yaml
Labels: approved, size/S

#3 fix: add the serviceAccountName
  README.md
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-csharp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-filerunner-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-buildtemplate.yaml
  jx-build-templates/templates/jenkins-gradle-buildtemplate.yaml
  jx-build-templates/templates/jenkins-javascript-buildtemplate.yaml
  jx-build-templates/templates/jenkins-jenkins-buildtemplate.yaml
  jx-build-templates/templates/jenkins-maven-buildtemplate.yaml
  jx-build-templates/templates/jenkins-python-buildtemplate.yaml
  jx-build-templates/templates/jenkins-rust-buildtemplate.yaml
  jx-build-templates/templates/jenkins-scala-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
Labels: approved, size/M

#6 fix: added jenkins-x-bot to the OWNERS file
  OWNERS
Labels: approved, size/XS

#18 fix: remove reference to builder-base images
  jx-build-templates/templates/knative-chart-ci-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-release-buildtemplate.yaml
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
  jx-build-templates/values.yaml
Labels: approved, size/S

#20 dummy commit
  README.md
Labels: approved, size/XS

#19 fix: duplicate buildsteps with the same name
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
Labels: approved, size/XS

#21 fix: removed invalid argument to helm init
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
Labels: approved, size/XS

#22 fix: dummy commit to trigger a release
  README.md
Labels: size/XS

#23 fix: using builder-base tags for knative
  jx-build-templates/templates/knative-chart-ci-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-release-buildtemplate.yaml
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
  jx-build-templates/values.yaml
Labels: approved, size/S
