Repository jenkins-x-charts/jx-build-templates, pull requests merged in 2019-01, with the labels that each got.

#289 fix: mount the maven settings xml for the cwp builder
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
Labels: approved, size/XS

#292 Add elixir build template
  jx-build-templates/templates/jenkins-elixir-buildtemplate.yaml
Labels: approved, ok-to-test, size/M

#290 feat: increased java memory for CWP build template
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
Labels: approved, size/XS

#298 fix: add some go based build templates
  jx-build-templates/templates/jenkins-go-script-ci-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-script-release-buildtemplate.yaml
Labels: approved, size/L

#357 Removed filerunner template as it has no dependencies installed
  jx-build-templates/templates/jenkins-filerunner-buildtemplate.yaml
Labels: approved, size/M

#376 feat: ruby buildtemplate
  jx-build-templates/templates/jenkins-ruby-buildtemplate.yaml
Labels: approved, ok-to-test, size/M
