Repository jenkins-x-charts/jx-build-templates, pull requests merged in 2019-03, with the labels that each got.

#453 switch builder images to gcr.io from docker.io
  jx-build-templates/templates/environment-apply-buildtemplate.yaml
  jx-build-templates/templates/environment-build-buildtemplate.yaml
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-csharp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-cwp-buildtemplate.yaml
  jx-build-templates/templates/jenkins-elixir-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-nodocker-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-script-bdd-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-script-ci-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-script-release-buildtemplate.yaml
  jx-build-templates/templates/jenkins-gradle-buildtemplate.yaml
  jx-build-templates/templates/jenkins-javascript-buildtemplate.yaml
  jx-build-templates/templates/jenkins-jenkins-buildtemplate.yaml
  jx-build-templates/templates/jenkins-maven-buildtemplate.yaml
  jx-build-templates/templates/jenkins-python-buildtemplate.yaml
  jx-build-templates/templates/jenkins-ruby-buildtemplate.yaml
  jx-build-templates/templates/jenkins-rust-buildtemplate.yaml
  jx-build-templates/templates/jenkins-scala-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-ci-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-release-buildtemplate.yaml
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
  jx-build-templates/templates/knative-maven-ci-buildtemplate.yaml
  jx-build-templates/templates/knative-maven-release-buildtemplate.yaml
Labels: approved, size/M

#462 switch builder-base to builder-jx
  jx-build-templates/templates/environment-apply-buildtemplate.yaml
  jx-build-templates/templates/environment-build-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-ci-buildtemplate.yaml
  jx-build-templates/templates/knative-chart-release-buildtemplate.yaml
  jx-build-templates/templates/knative-deploy-buildtemplate.yaml
Labels: approved, size/S

#481 feat: added test to validate images
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-go-script-bdd-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
  jx/scripts/test.sh
Labels: approved, size/L

#491 (Feat) Tekton build pack
  Makefile
  jenkins-x.yml
  jx-build-templates/Makefile
Labels: approved, size/M

#495 fix: reinstated jenkins-base build templates with correct image name
  jx-build-templates/templates/jenkins-base-buildtemplate.yaml
  jx-build-templates/templates/jenkins-test-buildtemplate.yaml
  jx-build-templates/values.yaml
Labels: approved, size/L

#497 feat: attempting to add in test phase into build
  Makefile
  jx/scripts/test.sh
Labels: approved, size/XS
